# Generated by Django 6.0.5 on 2026-06-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(default='', max_length=30, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='', max_length=30, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
