# Generated by Django 6.0.5 on 2026-06-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_specialisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='filiere',
        ),
    ]
