# Generated by Django 6.0.5 on 2026-06-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_filiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='specialisation',
            new_name='filiere',
        ),
    ]
