# Generated by Django 6.0.5 on 2026-06-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialisation',
            field=models.CharField(default='IA', max_length=50),
            preserve_default=False,
        ),
    ]
